config/routes.rb
Happyhour::Application.routes.draw do
resources :bars
resources :users
resource :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

end

app/models/bar.rb
  class Bar
  include Mongoid::Document
  include Mongoid::Paperclip

  has_mongoid_attached_file :image
  validates_attachment_content_type :image , :content_type => /\Aimage\/.*\Z/

  field :name, type: String
  field :category, type: String
  field :location, type: String
  field :contact, type: String


 has_and_belongs_to_many :users

end

app/models/user.rb
require "bcrypt"
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 include ApplicationHelper

 # helper_method :current_user
  def authenticate_user
    if !self.current_user
     	redirect_to new_sessions_path
    end
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController

before_action :authenticate_user

  def index
    @bars = Bar.all
  end

  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(params.require(:bar).permit(:name, :category, :location, :contact, :image))
      if @bar.save
        redirect_to bars_path
      else
        render 'new'
      end
  end


  def edit
    @bar = Bar.find(params[:id])
  end

  def show
    @bar = Bar.find(params[:id])
  end
  
  def update
    @bar = Bar.find(params[:id])
    if @bar.update(params.require(:bar).permit(:name, :category, :location, :contact, :image))
      redirect_to bars_path
    else
      render 'edit'
    end
  end

  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy
    redirect_to :root
  end


  private
    def verify_logged_in
    if !current_user
      flash[:error] = "You must log in!!!"
      redirect_to new_sessions_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      flash[:success] = "You have LOGGED IN successfully!"
      redirect_to bars_path
    end
  end

  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def index
   	@users = User.all 
  	end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :password, :email))
      if @user.save
        session[:remember_token] = @user.id
        @current_user = @user
        flash[:success] = "You have signed up successfully!"
        redirect_to bars_path
      else
        render 'new'
      end
  end


  def show
    @user = User.find(params[:id])
  end
  
  def update
  end

  def destroy
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user

 	#Or or method equal (Memoization) - sets this thing ONCE and don't reset. Current user - if current user is already set(or evaluates to truthy), don't do anything, just leave the value as it is
   if session[:remember_token]
   	@current_user ||= User.find(session[:remember_token])
   else
	@current_user = nil
   end
   end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bars/_form.html.erb
<%= form_for @bar do |b| %>
<div class = "barform">
	<div class = "smallerform">
	 <span class ="text">Name:</span> <%= b.text_field :name %> <br />
	</div>

	<div class = "smallerform">
	  <span class = "text">Category:</span>  <%= b.select :category, [['Select a Type','Select a Type'], ['Dive','Dive'],['Lounge','Lounge'],['Sports Bar','Sports Bar'], ['Pub', 'Pub'], ['Karaoke', 'Karaoke'], ['Hookah', 'Hookah'], ['Jazz','Jazz']] %> <br />
	</div>

	<div class = "smallerform">
	  <span class = "text">Location:</span> <%= b.text_field :location %> <br />
	</div>

	<div class = "smallerform">
	   <span class = "text">Contact</span> <%= b.text_field :contact %> <br />
	</div>

	<%= b.file_field :image %>
	<div class = "smallerform"><%= b.submit %></div>


<% end %>

app/views/bars/edit.html.erb
<%= render 'form' %>
	


	

app/views/bars/index.html.erb
																																										
<div class="row">
	<% @bars.each do |b| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="" alt="">
      <div class="caption">
      	<dl>
      	Name: <%= link_to bar_path b do %>
        	<dt><%= b.name %></dt>
        </dl>    
      </div>
    </div>
  </div>



  <% end %>
  <% end %>

</div>

app/views/bars/new.html.erb
<h1 id ="newbarform">Add a New Bar!</h1>

<%= render 'form' %>


<%= link_to "Back!", bars_path%>

app/views/bars/show.html.erb
<div class = "showpage">
		<h1> <u><em>Information Page</u></em></h1>
			<em>Name:</em> &nbsp;<span class = "editlabel"><%= @bar.name %></span>
		<br />
			<em>Location:</em>&nbsp; <%= @bar.location %>
		<br />
			<em>Contact:</em>&nbsp; <%= @bar.contact %>
		<br />
			<em>Category:</em>&nbsp; <%= @bar.category %>
	</div>

<%= image_tag @bar.image.url %>
<button id ="delete" type = "button"><%= link_to "Delete This Bar", @bars, method: :delete %></button>
<button id="edit" type="button"><%= link_to "Edit this Bar", edit_bar_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyhourApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
</head>
<body>
  
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <% if !current_user %>
          <li><button type="button" class="btn btn-default btn-lg">
              <i class="fa fa-home"></i><%= link_to "HAPPY HOUR!", root_path %>
            </button>
          </li>

          <% else %>
          <li><button type="button" class="btn btn-default btn-lg">
              <i class="fa fa-home"></i><%= link_to "HAPPY HOUR!", root_path %>
            </button>
          </li>
               
         <li><button type="button" class="btn btn-default btn-lg">
              <i class="fa fa-beer"></i></i> <%= link_to "VIEW BARS", bars_path %>
            </button>
        </li>

        <li><button type="button" class="btn btn-default btn-lg">
              <i class="fa fa-plus"></i></i><%= link_to "ADD BAR",  new_bar_path %>
            </button> 
        </li>

          <% end %>



      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><button type="button" class="btn btn-default btn-lg"><%= link_to "Sign Up", new_user_path %> </button> </li>
          <li><button type="button" class="btn btn-default btn-lg"><%= link_to "Sign In", new_sessions_path %></button></li>
        <% else %>
          <li id = "dof"><%= "Hello " + current_user.name.capitalize + " !" %></li>
          <li> <%= link_to "Sign Out", sessions_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
    </div>  <!-- /.container-fluid -->
  </nav>



<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<div id ="signup">
	<h1>New User</h1>
<%= form_for @user do |f| %>
<div class = "smallerform">
  Name: <%= f.text_field :name, :placeholder => "Type your Name" %>
</div>

<div class = "smallerform">
  Email: <%= f.text_field :email, :placeholder => "Type your Email" %>
</div>

<div class = "smallerform">
  Password: <%= f.password_field :password, :placeholder => "Enter your Password" %>
</div>
  <%= f.submit %>
<% end %>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1> IT'S HAPPYHOUR SOMEWHERE</h1>

<i class="fa fa-rebel fa-lg"></i>
  </div>
</div>